# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Mi-Memoir-App' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mi-Memoir-App
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod ''


end
